### PR TITLE
Experimental support of Turbolinks 3

### LINKED ISSUE #4: Add support for partial page replacement strategies with Turbograft
https://github.com/Shopify/turbograft

### PR DESCRIPTION
**Pull request by tortuetorche**
The goal of this pull request is just to show how we can support Turbolinks 3 in Symfony/Laravel.
I'm open to any suggestions and/or modifications!

Warning: This is an alpha version, it isn't production-ready yet.

Bonus: You can play with this [online demo](http://turbo3.herokuapp.com) (built with Laravel).
And you can grab the source code of this demo [here](https://github.com/efficiently/laravel_larasset_app/tree/turbo3-l5.1).

Should fix #4

### CODE REVIEW

**Comment by tortuetorche** [comment]
For the Laravel users: you can found [here](https://github.com/efficiently/turbolinks/commit/6ef12ccae8614cef9bdcd1bfbe57b72defe8910f) the Turbolinks 3 stuff.
I plan to merge it in the [Frenzy Turbolinks](https://github.com/frenzyapp/turbolinks/) repository later.

**Comment by carlalexander** [comment]
Thanks for that! I'll leave this here for when the new version is released.

**Comment by carlalexander** [comment]
In light of some of the [recent information about Turbolinks development](https://github.com/rails/turbolinks/issues/612), this PR is probably not going to get merged as it stands. For now, I'll leave it open for anyone using it. 

I plan on working on migrating the component to v5 when they start merging the work they're doing at Basecamp upstream. Until then, the recommendation is to stick with the current stable version,

**Comment by tortuetorche** [comment]
Hi @carlalexander,

I think the PHP code for Turbolinks 5 will not be so much different than this one for Turbolinks 3.
So, I will push a new pull request for Turbolinks 5, when it will be ready.

Cheers,
Tortue Torche.

**Comment by carlalexander** [comment]
Did you ever get anything working for Turbolinks 5?

**Comment by tortuetorche** [comment]
Hi @carlalexander,

Yes, I did.

I can send a new pull request for the Turbolinks 5 compatibility, if you want.

Cheers,
Tortue Torche

**Comment by carlalexander** [comment]
I'll close this one then. 😃

**Pull request closed without merging**
