### PR TITLE
Support of Turbolinks 5 on the server side.

### PR DESCRIPTION
**Pull request by tortuetorche**
Based on https://github.com/turbolinks/turbolinks-rails

FYI, [jQuery Turbolinks](https://github.com/kossnocorp/jquery.turbolinks) doesn't support Turbolinks 5, see https://github.com/kossnocorp/jquery.turbolinks/issues/56.
So you can use https://github.com/rstacruz/onmount or https://github.com/wshostak/turbolinks-jquery instead.

For [Laravel](http://laravel.com) framework support, see https://github.com/efficiently/turbolinks/tree/turbo5 and these snippets:

Put this code in your `app/Http/Controllers/Controller.php` file:

``` php
    //...

    /**
     * @param  string $path URL
     * @param  array $options Default to: ['status' => 302, 'headers' => [], 'secure' => null]
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function redirectTo($path, $options = [])
    {
        $defaultOptions = ['status' => 302, 'headers' => [], 'secure' => null];
        $options = array_merge($defaultOptions, $options);
        if (response()->hasMacro('redirectToWithTurbolinks')) {
            return response()->redirectToWithTurbolinks($path, $options);
        }
        return response()->redirectTo($path, $options['status'], $options['headers'], $options['secure']);
    }
    //...
```

**NOTE:** The `redirectToWithTurbolinks()` code is [here](https://github.com/efficiently/turbolinks/blob/turbo5/src/Frenzy/Turbolinks/TurbolinksServiceProvider.php#L85).

Then in your `app/Http/Controllers/MessagesController.php` file:

``` php
    //...
    public function store()
    {
        $inputs = Input::except('_method', '_token');
        $validator = Validator::make($inputs, Message::$rules);

        if ($validator->passes() && $message = Message::create($inputs)) {
            return $this->redirectTo(route('messages.show', $message->id));
        }

        return $this->redirectTo(route('messages.create'))->withInput()
            ->with('error', "Error: Unable to save this message");
    }
    //...
```

Specific Turbolinks options of the `$options` parameter can be passed to the  `->redirectTo()` method (<small>or  `->redirectToWithTurbolinks()` macro</small>):

``` php
<?php
$options = ['turbolinks' => false]; // skip turbolinks redirection, if the `turbolinks` option is identical (===) to false
$options = []; // turbolinks default redirection behavior, the `replace` action
$options = ['turbolinks' => 0]; // turbolinks default redirection behavior, the `replace` action
$options = ['turbolinks' => '']; // turbolinks default redirection behavior, the `replace` action
$options = ['turbolinks' => null]; // turbolinks default redirection behavior, the `replace` action
$options = ['turbolinks' => 'any_other_string_than_advance']; // turbolinks default redirection behavior, the `replace` action
$options = ['turbolinks' => 'advance']; // turbolinks custom redirection, with the `advance` action
```

**NOTE:** During an `advance` redirection, Turbolinks pushes a new entry onto the browser’s history stack using history.pushState.

<hr>

Related to #9
For Turbolinks 3, see https://github.com/helthe/Turbolinks/pull/6

Have a good day,
Tortue Torche

### CODE REVIEW

**Comment by tortuetorche** [comment]
You can download a Laravel demo application which uses Turbolinks 5, here:
https://github.com/efficiently/laravel_larasset_app/tree/turbo5-l5.1#readme

**Comment by carlalexander** [comment]
Thanks! I'll try to look at it this week.

**Comment by tortuetorche** [comment]
Hi @carlalexander,

Any news on this pull request?

Cheers,
Tortue Torche

**Comment by carlalexander** [comment]
Sorry @tortuetorche, I ended up being swamped the last two weeks. There are conflicts with the merge that I need to look at. I also noticed some of the documentation badges are pointing to the wrong branch now.

I'll try to look at this over the weekend or next week. Sorry again for the delay.

**Comment by carlalexander** [comment]
So I've looked over the PR, everything in the `README.md` points to the `turbo5` branch and not `master`. I wouldn't remove `Resources/public/js/turbolinks.js` since other packages might have post install hooks for it. Instead, I'd replace it with the current [`turbolinks.js`](https://github.com/turbolinks/turbolinks/blob/v5.0.0/dist/turbolinks.js).

**Comment by tortuetorche** [comment]
Hi @carlalexander,

`Resources/public/js/turbolinks.js` isn't removed, just updated with https://github.com/turbolinks/turbolinks/blob/v5.0.0/dist/turbolinks.js

For jQuery compatibility, there is a new library https://github.com/wshostak/turbolinks-jquery which is compatible with Turbolinks 5, but I didn't test it yet.
Maybe we can switch to it, but it'll be better to do this in a second pull-request.

Have a good day

**Comment by tortuetorche** [comment]
I updated this pull request description to explain how we can use Turbolinks options on the server side.

**Comment by carlalexander** [comment]
Thanks @tortuetorche! Sorry, been swamped and haven't looked into the new stuff 😞

**Comment by UFOMelkor** [comment]
Works like a charm for me :+1:

**Comment by tortuetorche** [comment]
My pull request is ready to be merged 🚀
Of course, we can do some refactoring, add more tests and docs.
But, the main goal of porting Turbolinks 5 is done 👍

Happy New Year 2017 🎆

**Comment by carlalexander** [comment]
Thanks for your all your work @tortuetorche!

**Pull request merged**
