### PR TITLE
Update dependencies to allow Symfony 4.0

### PR DESCRIPTION
**Pull request by kyranb**

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
This would be great! Running into an issue with Laravel 5.6 and Symfony 4+ components

**Comment by tortuetorche** [comment]
Hi @carlalexander,
Do you plan to merge this pull request?
It'll be also useful for the [frenzy/turbolinks](https://github.com/frenzyapp/turbolinks) package.

Have a good day,
Tortue Torche

**Comment by carlalexander** [comment]
Yes! Sorry about that. Will merge later today.

**Comment by carlalexander** [comment]
Tagged a new version as well

**Pull request merged**
